### ISSUE TITLE
RangeError (index): Invalid value: Only valid value is 0: -1

### ISSUE THREAD

**Issue by Sarat-1997** [YashMakan/Youtube-Whatsapp-Clone#3]
ScrollablePositionedList.builder(
                          shrinkWrap: true,
                          scrollDirection: Axis.vertical,
                          itemScrollController: scrollController,
                          itemCount: messages.length,
                          itemBuilder: (context, index) {
                            return messages[index];
    }

                        ),

**Comment by YashMakan** [comment]
Thanks for informing, this issue is fixed with the part 13 branch. 
https://www.youtube.com/watch?v=J1pbXSyUIFg
